spring:
  application:
    name: kotlin-commerce
  profiles:
    active: local
  datasource:
    name: CommerceDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate

---
spring.config.activate.on-profile: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/commerce?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: application
    password: application

app:
  redisson:
    mode: single
    address: redis://localhost:6379
    database: 0